
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Charging
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Threshold Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Charging[32] = {
    // ███∙∙█████∙∙███
    // ███∙∙█████∙∙███
    // ███∙∙█████∙∙███
    // ███∙∙█████∙∙███
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙█████████████∙
    // ∙█████████████∙
    // █∙███████████∙█
    // █∙███████████∙█
    // ██∙█████████∙██
    // ███∙∙█████∙∙███
    // █████∙∙∙∙∙█████
    // ██████∙█∙██████
    // ██████∙█∙██████
    // ██████∙█∙██████
    // ██████∙∙∙██████
    0xe7, 0xce, 
    0xe7, 0xce, 
    0xe7, 0xce, 
    0xe7, 0xce, 
    0x00, 0x00, 
    0x7f, 0xfc, 
    0x7f, 0xfc, 
    0xbf, 0xfa, 
    0xbf, 0xfa, 
    0xdf, 0xf6, 
    0xe7, 0xce, 
    0xf8, 0x3e, 
    0xfd, 0x7e, 
    0xfd, 0x7e, 
    0xfd, 0x7e, 
    0xfc, 0x7e
};
const tImage Charging = { image_data_Charging, 15, 16,
    8 };

