
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: charging
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_charging[32] = {
    // ∙∙∙██∙∙∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙∙∙██∙∙∙
    // ∙∙∙██∙∙∙∙∙██∙∙∙
    // ███████████████
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // █∙∙∙∙∙∙∙∙∙∙∙∙∙█
    // ∙█∙∙∙∙∙∙∙∙∙∙∙█∙
    // ∙█∙∙∙∙∙∙∙∙∙∙∙█∙
    // ∙∙█∙∙∙∙∙∙∙∙∙█∙∙
    // ∙∙∙██∙∙∙∙∙██∙∙∙
    // ∙∙∙∙∙█████∙∙∙∙∙
    // ∙∙∙∙∙∙█∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙█∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙█∙█∙∙∙∙∙∙
    // ∙∙∙∙∙∙███∙∙∙∙∙∙
    0x18, 0x30, 
    0x18, 0x30, 
    0x18, 0x30, 
    0x18, 0x30, 
    0xff, 0xfe, 
    0x80, 0x02, 
    0x80, 0x02, 
    0x40, 0x04, 
    0x40, 0x04, 
    0x20, 0x08, 
    0x18, 0x30, 
    0x07, 0xc0, 
    0x02, 0x80, 
    0x02, 0x80, 
    0x02, 0x80, 
    0x03, 0x80
};
const tImage charging = { image_data_charging, 15, 16,
    8 };

