
/*******************************************************************************
* generated by lcd-image-converter rev.030b30d from 2019-03-17 01:38:34 +0500
* image
* filename: unsaved
* name: Battery
*
* preset name: Monochrome
* data block size: 8 bit(s), uint8_t
* RLE compression enabled: no
* conversion type: Monochrome, Diffuse Dither 128
* split to rows: yes
* bits per pixel: 1
*
* preprocess:
*  main scan direction: top_to_bottom
*  line scan direction: forward
*  inverse: no
*******************************************************************************/

/*
 typedef struct {
     const uint8_t *data;
     uint16_t width;
     uint16_t height;
     uint8_t dataSize;
     } tImage;
*/
#include <stdint.h>



static const uint8_t image_data_Battery[30] = {
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    // ∙∙∙∙∙█████∙∙∙∙∙
    // ∙∙∙█████████∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█∙∙∙∙∙∙∙█∙∙∙
    // ∙∙∙█████████∙∙∙
    // ∙∙∙∙∙∙∙∙∙∙∙∙∙∙∙
    0x00, 0x00, 
    0x07, 0xc0, 
    0x1f, 0xf0, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x10, 0x10, 
    0x1f, 0xf0, 
    0x00, 0x00
};
const tImage Battery = { image_data_Battery, 15, 15,
    8 };

